name = "anidash"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-04-01"

[vars]
VITE_MAL_CLIENT_ID = "3e45fccd29b9aec2aeee18ad8a9ad46d"
MAL_CLIENT_ID = "3e45fccd29b9aec2aeee18ad8a9ad46d"
